owner: CapellaWS # GitHub username force
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Platform Hybrid Working
    url: https://hybrid.capella-ws.com
  - name: Domus
    url: https://portal.capella.ie
  - name: Website-com
    url: https://capella-ws.com
  - name: Website-ie
    url: https://capella.ie
assignees: # Users to assign downtime issues (optional)
  - carlos-cws
status-website: # Status website (optional)  
  name: Upptime # Status website title
  apiBaseUrl: https://api.github.com
