owner: CapellaWS # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Platform Hybrid Working
    url: https://hybrid.capella-ws.com
  - name: Domus
    url: https://portal.capella.ie
assignees: # Users to assign downtime issues (optional)
  - carlos-ws
status-website: # Status website (optional)  
  name: Upptime # Status website title
